
-- IDEMPOTENT UPSERT SEED SCRIPT
-- Run this AFTER 20260907000001_unclaimed_doctors.sql is applied

INSERT INTO public.doctor_profiles 
  (doctor_id, slug, public_display_name, professional_summary, years_of_experience, city, state, publication_status, data_status, offers_home_visits, home_visit_service_areas)
VALUES
  ('c6f78a40-9fda-575e-9e51-a61c11fd71f9', 'dr-abhidha-shah', 'Dr. Abhidha Shah', 'Medical professional specializing in Neurosurgeon.', 18, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('3663651a-cc01-57ea-8f1f-b6d991397c4c', 'dr-girish-nair', 'Dr. Girish Nair', 'Medical professional specializing in Neurologist.', 29, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('3a79cb8e-46f1-5f8f-81c1-573801ad9392', 'dr-nitin-dange', 'Dr. Nitin Dange', 'Medical professional specializing in Neurosurgeon.', 22, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('4f8e3efe-4a4f-5006-8227-c41d3132148d', 'dr-rahul-gupta', 'Dr. Rahul Gupta', 'Medical professional specializing in Cardiologist.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('e3ddf2e2-208e-532e-ab9f-d5de891fd068', 'dr-sanjeevkumar-r-kalkekar', 'Dr. Sanjeevkumar R. Kalkekar', 'Medical professional specializing in Cardiologist.', 26, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('617c45e3-573f-5615-8025-835caa0b4690', 'dr-anjali-kumar', 'Dr. Anjali Kumar', 'Medical professional specializing in Gynecologist.', 18, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('b06980d7-5e6e-59c2-9cb7-acf128e79d41', 'dr-kishore-kumar', 'Dr. Kishore Kumar', 'Medical professional specializing in Neonatologist.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('d26f6289-b659-50a1-a7ef-bd7e292500a3', 'dr-meera-k', 'Dr. Meera K.', 'Medical professional specializing in Obstetrician.', 15, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('3a13f61f-ed18-5ec7-b5b8-04359dc2181d', 'dr-ritu-hinduja', 'Dr. Ritu Hinduja', 'Medical professional specializing in Fertility Specialist.', 14, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('d2749ac3-f633-5bd8-bf1d-418cd55bd0fa', 'dr-swati-sinha', 'Dr. Swati Sinha', 'Medical professional specializing in Pediatrician.', 12, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('ab97ab5d-6672-5424-b8c7-ab00549cae68', 'dr-donald-john-babu', 'Dr. Donald John Babu', 'Medical professional specializing in Surgical Oncologist.', 21, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('1c0c3091-e610-5fa9-8196-55213ebaa94a', 'dr-kapil-mohan', 'Dr. Kapil Mohan', 'Medical professional specializing in Spine Surgeon (Ortho).', 23, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('9dd88ae2-0fb2-55e4-99dd-204d99e5d059', 'dr-nandini-gupta', 'Dr. Nandini Gupta', 'Medical professional specializing in Dermatologist.', 19, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('504b224a-335a-5cbc-9520-5ecacb671680', 'dr-shilpa-deshmukh-kadam', 'Dr. Shilpa Deshmukh Kadam', 'Medical professional specializing in Cardiologist.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('89657a46-d6bf-508a-8eea-601b6c5f3be1', 'dr-vinita-goyle', 'Dr. Vinita Goyle', 'Medical professional specializing in ENT.', 37, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('6c2d7b00-de7f-5174-ba62-f0365a0ed23c', 'dr-bipin-jiwnani', 'Dr. Bipin Jiwnani', 'Medical professional specializing in Orthopedic Surgeon.', 20, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('a3ff0ea0-81aa-55b7-88df-c6fbaf0d68de', 'dr-deepak-aiwale', 'Dr. Deepak Aiwale', 'Medical professional specializing in Neurologist.', 23, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('c2aa85fc-a899-57e2-811e-314d6de1a99e', 'dr-deepak-p-kumar', 'Dr. Deepak P. Kumar', 'Medical professional specializing in Radiation Oncologist.', 16, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('9f1ba27e-1869-5d6c-a918-9acda09d9f8f', 'dr-hitendra-patil', 'Dr. Hitendra Patil', 'Medical professional specializing in Surgical Oncologist.', 24, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('6b4a603a-10c6-59fd-8e8f-d0f1b7559749', 'dr-niraj-kumar', 'Dr. Niraj Kumar', 'Medical professional specializing in Cardiologist.', 11, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('6d3310a7-35d7-5c0d-a96f-cd6236dd5bb5', 'dr-c-s-pramesh', 'Dr. C.S. Pramesh', 'Medical professional specializing in Thoracic Surgeon.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('c8c98727-ddd8-594c-ad87-e9e315856508', 'dr-pankaj-chaturvedi', 'Dr. Pankaj Chaturvedi', 'Medical professional specializing in Head & Neck Surgeon.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('130b44b6-2f48-51bd-8ea1-d24f8e585682', 'dr-rajiv-sarin', 'Dr. Rajiv Sarin', 'Medical professional specializing in Radiation Oncologist.', 30, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('548ece8c-6d40-53db-b49b-ab5e5fdffc34', 'dr-shailesh-shrikhande', 'Dr. Shailesh Shrikhande', 'Medical professional specializing in Gastrointestinal Oncologist.', 26, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('967a9937-b440-5785-b399-2b37f5ed8526', 'dr-sudeep-gupta', 'Dr. Sudeep Gupta', 'Medical professional specializing in Medical Oncologist.', 28, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('7b8b030b-b84d-582a-9f2c-3e8320b9e72a', 'dr-anup-ramani', 'Dr. Anup Ramani', 'Medical professional specializing in Uro-Oncologist.', 26, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('be29367e-0389-5724-af07-a9443edc6255', 'dr-kedar-toraskar', 'Dr. Kedar Toraskar', 'Medical professional specializing in Critical Care.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'verified', false, NULL),
  ('23c2f20d-4b69-519b-95e3-bc1f1f2cece3', 'dr-prashant-makhija', 'Dr. Prashant Makhija', 'Medical professional specializing in Neurologist.', 18, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('544e1465-358f-5d73-a1bf-a314d9d4d775', 'dr-rajendra-patankar', 'Dr. Rajendra Patankar', 'Medical professional specializing in General Medicine.', 25, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('0610e398-fefa-5312-8c90-4d778988a530', 'dr-sameer-kulkarni', 'Dr. Sameer Kulkarni', 'Medical professional specializing in Orthopedics.', 20, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', false, NULL),
  ('0044ae64-3231-5d64-9730-b544b1e052a7', 'dr-shwet-v-sabnis', 'Dr. Shwet V. Sabnis', 'General practitioner offering home visits in Seawoods.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Seawoods']),
  ('23cfb554-1887-5523-95fe-110d2f2fe28c', 'dr-ritu-khemani', 'Dr. Ritu Khemani', 'General practitioner offering home visits in Kopar Khairane.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Kopar Khairane']),
  ('4d631234-af1a-55c2-9b03-104533668c84', 'dr-pankaj-sawant', 'Dr. Pankaj Sawant', 'General practitioner offering home visits in Navi Mumbai (Multiple Sectors).', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai (Multiple Sectors)']),
  ('e29a609e-1663-5e69-ae84-69f1517228b7', 'dr-omkar-kiwlekar', 'Dr. Omkar Kiwlekar', 'General practitioner offering home visits in Nerul.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Nerul']),
  ('d277b55c-ab37-571e-ba46-3bc06510b7a7', 'dr-pooja-bharadwaj', 'Dr. Pooja Bharadwaj', 'General practitioner offering home visits in Nerul.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Nerul']),
  ('863490f9-ec83-56a5-9dce-54dc54ca3306', 'dr-ujwal-ramteke', 'Dr. Ujwal Ramteke', 'General practitioner offering home visits in Nerul.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Nerul']),
  ('e47ad43e-e9a6-5cfc-adb0-42cf7e532655', 'dr-nitin-laxmikant-meher', 'Dr. Nitin Laxmikant Meher', 'General practitioner offering home visits in Kharghar.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Kharghar']),
  ('7c8986ad-4f08-56c8-afae-224d1aa1b890', 'dr-devvrat-s-parekh', 'Dr. Devvrat S. Parekh', 'General practitioner offering home visits in Vashi.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Vashi']),
  ('8e2c12f6-d2aa-5892-b12e-7a9839c4bdc8', 'dr-maulik-n-mehta', 'Dr. Maulik N. Mehta', 'General practitioner offering home visits in Vashi.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Vashi']),
  ('ca994cf8-36ab-5045-a4c4-f1eedefbabd5', 'dr-sandeep-guthe', 'Dr. Sandeep Guthe', 'General practitioner offering home visits in Vashi.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Vashi']),
  ('669df586-2c60-5cd3-988b-7afeb7d66c86', 'dr-vignan-rachabattuni', 'Dr. Vignan Rachabattuni', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('17ca5109-ec7b-5214-982c-a72242bd93bb', 'vaidya-kanchan', 'Vaidya Kanchan', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('72e92e9d-531c-5374-827d-58f1f5285435', 'dr-soopti-khare', 'Dr. Soopti Khare', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('df7645e4-98f2-5267-8e66-4357a2f6eb27', 'dr-virendar-sarwal', 'Dr. Virendar Sarwal', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('03c0bb89-ae9a-545a-a728-3e94a886788f', 'dr-chakravarthy-mazumdar-j-k', 'Dr. Chakravarthy Mazumdar J K', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('7ec847b3-c81c-5551-a1bd-eafe21d5fe48', 'dr-yagnang-kaushikkumar-vyas', 'Dr. Yagnang Kaushikkumar Vyas', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('b95fd920-e5f2-5145-ba82-5a3a86166c31', 'dr-major-urvashi-shetty', 'Dr. (Major) Urvashi Shetty', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('4e39ec5c-5cb7-594a-b82d-925ca6d707bf', 'dr-emad-mohammed', 'Dr. Emad Mohammed', 'General practitioner offering home visits in Navi Mumbai.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Navi Mumbai']),
  ('5cae0f8b-116b-54c5-8bb9-1138d10549d7', 'dr-neha-suryawanshi', 'Dr. Neha Suryawanshi', 'General practitioner offering home visits in Nerul.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Nerul']),
  ('af9445ea-1b02-5e9c-a6f1-37483c114265', 'dr-c-s-shobha', 'Dr. C.S. Shobha', 'General practitioner offering home visits in Nerul.', NULL, 'Navi Mumbai', 'Maharashtra', 'published', 'pending', true, ARRAY['Nerul'])
ON CONFLICT (slug) DO UPDATE SET
  public_display_name = EXCLUDED.public_display_name,
  professional_summary = EXCLUDED.professional_summary,
  years_of_experience = COALESCE(doctor_profiles.years_of_experience, EXCLUDED.years_of_experience),
  offers_home_visits = EXCLUDED.offers_home_visits,
  home_visit_service_areas = EXCLUDED.home_visit_service_areas;
